"""Pure Manager Mode card economics and roster legality domain."""

from .cards import (
    TIER_POLICY_VERSION,
    AbilityRating,
    BatSide,
    CardCatalog,
    CardKind,
    CatalogEntry,
    PitcherRole,
    PlayerSeasonCard,
    ThrowSide,
    Tier,
    impact,
)
from .game_roster import (
    LineupEntry,
    PlateAppearanceSide,
    TeamGameRoster,
    begin_batting_pa,
    begin_fielding_pa,
    change_pitcher,
    complete_batting_pa,
    complete_fielding_pa,
    create_team_game_roster,
    enable_emergency_extension,
    pinch_hit,
    pitcher_bf_capacity,
)
from .game_simulation import (
    ManagerGameResult,
    ManagerGameSession,
    PitcherSubstitutionEvent,
    create_manager_game,
    simulate_manager_game,
    simulate_manager_next_pa,
)
from .league import (
    MANAGER_LEAGUE_VERSION,
    ManagerLeagueState,
    ManagerTeamConfig,
    ManagerTeamState,
    create_manager_league,
    simulate_league_games,
    simulate_manager_season,
    simulate_next_league_game,
)
from .loader import RATING_ARTIFACT_SCHEMA, load_card_catalog
from .optimizer import OptimizedRoster, RosterStrategy, build_optimized_roster
from .roster import RosterLegality, RosterRules, RosterSelection, evaluate_roster
from .season import GameResult, ScheduledGame, Standing, Standings, generate_schedule
from .usage import (
    PitcherAvailability,
    PitcherUsageEvent,
    apply_pitcher_usage,
    available_bullpen,
    create_pitcher_availability,
    eligible_starters,
    replay_pitcher_usage,
    select_next_starter,
)

__all__ = [
    "TIER_POLICY_VERSION",
    "AbilityRating",
    "BatSide",
    "CardCatalog",
    "CardKind",
    "CatalogEntry",
    "GameResult",
    "LineupEntry",
    "MANAGER_LEAGUE_VERSION",
    "ManagerLeagueState",
    "ManagerGameResult",
    "ManagerGameSession",
    "ManagerTeamConfig",
    "ManagerTeamState",
    "OptimizedRoster",
    "PlateAppearanceSide",
    "PitcherRole",
    "PitcherAvailability",
    "PitcherSubstitutionEvent",
    "PitcherUsageEvent",
    "PlayerSeasonCard",
    "RATING_ARTIFACT_SCHEMA",
    "RosterLegality",
    "RosterRules",
    "RosterSelection",
    "RosterStrategy",
    "ScheduledGame",
    "Standing",
    "Standings",
    "TeamGameRoster",
    "Tier",
    "ThrowSide",
    "apply_pitcher_usage",
    "available_bullpen",
    "begin_batting_pa",
    "begin_fielding_pa",
    "build_optimized_roster",
    "change_pitcher",
    "complete_batting_pa",
    "complete_fielding_pa",
    "create_team_game_roster",
    "enable_emergency_extension",
    "create_manager_game",
    "create_manager_league",
    "create_pitcher_availability",
    "eligible_starters",
    "evaluate_roster",
    "generate_schedule",
    "impact",
    "load_card_catalog",
    "pinch_hit",
    "pitcher_bf_capacity",
    "replay_pitcher_usage",
    "select_next_starter",
    "simulate_manager_game",
    "simulate_manager_season",
    "simulate_league_games",
    "simulate_manager_next_pa",
    "simulate_next_league_game",
]
